# Generated by cloudcoil-model-codegen v0.7.1
# DO NOT EDIT

from typing import Annotated, Callable, ClassVar, Literal, overload

from cloudcoil.apimachinery import ObjectMeta
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)
from cloudcoil.resources import Resource
from pydantic import Field


class ImageSpecImagePullSecretsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ImageSpecImagePullSecretsItem"]:
            return ImageSpecImagePullSecretsItem

        def build(self) -> "ImageSpecImagePullSecretsItem":
            return ImageSpecImagePullSecretsItem(**self._attrs)

        def name(self, value: str | None, /) -> Self:
            "Name of the referent.\nThis field is effectively required, but due to backwards compatibility is\nallowed to be empty. Instances of this type with an empty value here are\nalmost certainly wrong.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
            return self._set("name", value)

    class BuilderContext(BuilderContextBase["ImageSpecImagePullSecretsItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ImageSpecImagePullSecretsItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ImageSpecImagePullSecretsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["ImageSpecImagePullSecretsItem", Builder]:
        return GenericListBuilder[
            ImageSpecImagePullSecretsItem, ImageSpecImagePullSecretsItem.Builder
        ]()

    name: str | None = ""
    "Name of the referent.\nThis field is effectively required, but due to backwards compatibility is\nallowed to be empty. Instances of this type with an empty value here are\nalmost certainly wrong.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"


class ImageStatusConditionsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ImageStatusConditionsItem"]:
            return ImageStatusConditionsItem

        def build(self) -> "ImageStatusConditionsItem":
            return ImageStatusConditionsItem(**self._attrs)

        def last_transition_time(self, value: str | None, /) -> Self:
            "LastTransitionTime is the last time the condition transitioned from one status to another.\nWe use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic\ndifferences (all other things held constant)."
            return self._set("last_transition_time", value)

        def message(self, value: str | None, /) -> Self:
            "A human readable message indicating details about the transition."
            return self._set("message", value)

        def reason(self, value: str | None, /) -> Self:
            "The reason for the condition\u0027s last transition."
            return self._set("reason", value)

        def severity(self, value: str | None, /) -> Self:
            "Severity with which to treat failures of this type of condition.\nWhen this is not specified, it defaults to Error."
            return self._set("severity", value)

        def status(self, value: str, /) -> Self:
            "Status of the condition, one of True, False, Unknown."
            return self._set("status", value)

        def type(self, value: str, /) -> Self:
            "Type of condition."
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["ImageStatusConditionsItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ImageStatusConditionsItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ImageStatusConditionsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ImageStatusConditionsItem", Builder]:
        return GenericListBuilder[ImageStatusConditionsItem, ImageStatusConditionsItem.Builder]()

    last_transition_time: Annotated[str | None, Field(alias="lastTransitionTime")] = None
    "LastTransitionTime is the last time the condition transitioned from one status to another.\nWe use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic\ndifferences (all other things held constant)."
    message: str | None = None
    "A human readable message indicating details about the transition."
    reason: str | None = None
    "The reason for the condition\u0027s last transition."
    severity: str | None = None
    "Severity with which to treat failures of this type of condition.\nWhen this is not specified, it defaults to Error."
    status: str
    "Status of the condition, one of True, False, Unknown."
    type: str
    "Type of condition."


class ImageSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ImageSpec"]:
            return ImageSpec

        def build(self) -> "ImageSpec":
            return ImageSpec(**self._attrs)

        def image(self, value: str, /) -> Self:
            "Image is the name of the container image url to cache across the cluster."
            return self._set("image", value)

        @overload
        def image_pull_secrets(
            self, value_or_callback: list[ImageSpecImagePullSecretsItem] | None, /
        ) -> "ImageSpec.Builder": ...

        @overload
        def image_pull_secrets(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        ImageSpecImagePullSecretsItem,
                        ImageSpecImagePullSecretsItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    ImageSpecImagePullSecretsItem, ImageSpecImagePullSecretsItem.Builder
                ]
                | list[ImageSpecImagePullSecretsItem],
            ],
            /,
        ) -> "ImageSpec.Builder": ...

        @overload
        def image_pull_secrets(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[ImageSpecImagePullSecretsItem.Builder]: ...

        def image_pull_secrets(self, value_or_callback=UNSET, /):
            "ImagePullSecrets contains the names of the Kubernetes Secrets containing login\ninformation used by the Pods which will run this container."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[ImageSpecImagePullSecretsItem.Builder]()
                context._parent_builder = self
                context._field_name = "image_pull_secrets"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ImageSpecImagePullSecretsItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("image_pull_secrets", value)

        def service_account_name(self, value: str | None, /) -> Self:
            "ServiceAccountName is the name of the Kubernetes ServiceAccount as which the Pods\nwill run this container.  This is potentially used to authenticate the image pull\nif the service account has attached pull secrets.  For more information:\nhttps://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account"
            return self._set("service_account_name", value)

    class BuilderContext(BuilderContextBase["ImageSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ImageSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ImageSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ImageSpec", Builder]:
        return GenericListBuilder[ImageSpec, ImageSpec.Builder]()

    image: str
    "Image is the name of the container image url to cache across the cluster."
    image_pull_secrets: Annotated[
        list[ImageSpecImagePullSecretsItem] | None, Field(alias="imagePullSecrets")
    ] = None
    "ImagePullSecrets contains the names of the Kubernetes Secrets containing login\ninformation used by the Pods which will run this container."
    service_account_name: Annotated[str | None, Field(alias="serviceAccountName")] = None
    "ServiceAccountName is the name of the Kubernetes ServiceAccount as which the Pods\nwill run this container.  This is potentially used to authenticate the image pull\nif the service account has attached pull secrets.  For more information:\nhttps://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account"


class ImageStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ImageStatus"]:
            return ImageStatus

        def build(self) -> "ImageStatus":
            return ImageStatus(**self._attrs)

        def annotations(self, value: dict[str, str] | None, /) -> Self:
            "Annotations is additional Status fields for the Resource to save some\nadditional State as well as convey more information to the user. This is\nroughly akin to Annotations on any k8s resource, just the reconciler conveying\nricher information outwards."
            return self._set("annotations", value)

        @overload
        def conditions(
            self, value_or_callback: list[ImageStatusConditionsItem] | None, /
        ) -> "ImageStatus.Builder": ...

        @overload
        def conditions(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[ImageStatusConditionsItem, ImageStatusConditionsItem.Builder]],
                GenericListBuilder[ImageStatusConditionsItem, ImageStatusConditionsItem.Builder]
                | list[ImageStatusConditionsItem],
            ],
            /,
        ) -> "ImageStatus.Builder": ...

        @overload
        def conditions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[ImageStatusConditionsItem.Builder]: ...

        def conditions(self, value_or_callback=UNSET, /):
            "Conditions the latest available observations of a resource\u0027s current state."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[ImageStatusConditionsItem.Builder]()
                context._parent_builder = self
                context._field_name = "conditions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ImageStatusConditionsItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("conditions", value)

        def observed_generation(self, value: int | None, /) -> Self:
            "ObservedGeneration is the \u0027Generation\u0027 of the Service that\nwas last processed by the controller."
            return self._set("observed_generation", value)

    class BuilderContext(BuilderContextBase["ImageStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ImageStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ImageStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ImageStatus", Builder]:
        return GenericListBuilder[ImageStatus, ImageStatus.Builder]()

    annotations: dict[str, str] | None = None
    "Annotations is additional Status fields for the Resource to save some\nadditional State as well as convey more information to the user. This is\nroughly akin to Annotations on any k8s resource, just the reconciler conveying\nricher information outwards."
    conditions: list[ImageStatusConditionsItem] | None = None
    "Conditions the latest available observations of a resource\u0027s current state."
    observed_generation: Annotated[int | None, Field(alias="observedGeneration")] = None
    "ObservedGeneration is the \u0027Generation\u0027 of the Service that\nwas last processed by the controller."


class Image(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "images",
        "scope": "Namespaced",
        "status": True,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["Image"]:
            return Image

        def build(self) -> "Image":
            return Image(**self._attrs)

        def api_version(self, value: Literal["caching.internal.knative.dev/v1alpha1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["Image"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(self, value_or_callback: ObjectMeta | None, /) -> "Image.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "Image.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(self, value_or_callback: ImageSpec | None, /) -> "Image.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[[ImageSpec.Builder], ImageSpec.Builder | ImageSpec],
            /,
        ) -> "Image.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "ImageSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ImageSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ImageSpec.builder())
                if isinstance(output, ImageSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(self, value_or_callback: ImageStatus | None, /) -> "Image.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[[ImageStatus.Builder], ImageStatus.Builder | ImageStatus],
            /,
        ) -> "Image.Builder": ...

        @overload
        def status(self, value_or_callback: Never = ...) -> "ImageStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ImageStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ImageStatus.builder())
                if isinstance(output, ImageStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["Image.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = Image.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for Image."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["Image", Builder]:
        return GenericListBuilder[Image, Image.Builder]()

    api_version: Annotated[
        Literal["caching.internal.knative.dev/v1alpha1"], Field(alias="apiVersion")
    ] = "caching.internal.knative.dev/v1alpha1"
    "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["Image"] = "Image"
    "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    spec: ImageSpec | None = None
    status: ImageStatus | None = None
