# Generated by cloudcoil-model-codegen v0.7.0
# DO NOT EDIT

from typing import Annotated, Callable, ClassVar, Literal, overload

from cloudcoil.apimachinery import ObjectMeta
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)
from cloudcoil.resources import Resource
from pydantic import Field


class MetricSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["MetricSpec"]:
            return MetricSpec

        def build(self) -> "MetricSpec":
            return MetricSpec(**self._attrs)

        def panic_window(self, value: int, /) -> Self:
            "PanicWindow is the aggregation window for metrics where quick reactions are needed."
            return self._set("panic_window", value)

        def scrape_target(self, value: str, /) -> Self:
            "ScrapeTarget is the K8s service that publishes the metric endpoint."
            return self._set("scrape_target", value)

        def stable_window(self, value: int, /) -> Self:
            "StableWindow is the aggregation window for metrics in a stable state."
            return self._set("stable_window", value)

    class BuilderContext(BuilderContextBase["MetricSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = MetricSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for MetricSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["MetricSpec", Builder]:
        return GenericListBuilder[MetricSpec, MetricSpec.Builder]()

    panic_window: Annotated[int, Field(alias="panicWindow")]
    "PanicWindow is the aggregation window for metrics where quick reactions are needed."
    scrape_target: Annotated[str, Field(alias="scrapeTarget")]
    "ScrapeTarget is the K8s service that publishes the metric endpoint."
    stable_window: Annotated[int, Field(alias="stableWindow")]
    "StableWindow is the aggregation window for metrics in a stable state."


class MetricStatusConditionsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["MetricStatusConditionsItem"]:
            return MetricStatusConditionsItem

        def build(self) -> "MetricStatusConditionsItem":
            return MetricStatusConditionsItem(**self._attrs)

        def last_transition_time(self, value: str | None, /) -> Self:
            "LastTransitionTime is the last time the condition transitioned from one status to another.\nWe use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic\ndifferences (all other things held constant)."
            return self._set("last_transition_time", value)

        def message(self, value: str | None, /) -> Self:
            "A human readable message indicating details about the transition."
            return self._set("message", value)

        def reason(self, value: str | None, /) -> Self:
            "The reason for the condition\u0027s last transition."
            return self._set("reason", value)

        def severity(self, value: str | None, /) -> Self:
            "Severity with which to treat failures of this type of condition.\nWhen this is not specified, it defaults to Error."
            return self._set("severity", value)

        def status(self, value: str, /) -> Self:
            "Status of the condition, one of True, False, Unknown."
            return self._set("status", value)

        def type(self, value: str, /) -> Self:
            "Type of condition."
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["MetricStatusConditionsItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = MetricStatusConditionsItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for MetricStatusConditionsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["MetricStatusConditionsItem", Builder]:
        return GenericListBuilder[MetricStatusConditionsItem, MetricStatusConditionsItem.Builder]()

    last_transition_time: Annotated[str | None, Field(alias="lastTransitionTime")] = None
    "LastTransitionTime is the last time the condition transitioned from one status to another.\nWe use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic\ndifferences (all other things held constant)."
    message: str | None = None
    "A human readable message indicating details about the transition."
    reason: str | None = None
    "The reason for the condition\u0027s last transition."
    severity: str | None = None
    "Severity with which to treat failures of this type of condition.\nWhen this is not specified, it defaults to Error."
    status: str
    "Status of the condition, one of True, False, Unknown."
    type: str
    "Type of condition."


class PodAutoscalerSpecScaleTargetRef(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PodAutoscalerSpecScaleTargetRef"]:
            return PodAutoscalerSpecScaleTargetRef

        def build(self) -> "PodAutoscalerSpecScaleTargetRef":
            return PodAutoscalerSpecScaleTargetRef(**self._attrs)

        def api_version(self, value: str | None, /) -> Self:
            "API version of the referent."
            return self._set("api_version", value)

        def kind(self, value: str | None, /) -> Self:
            "Kind of the referent.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        def name(self, value: str | None, /) -> Self:
            "Name of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
            return self._set("name", value)

    class BuilderContext(BuilderContextBase["PodAutoscalerSpecScaleTargetRef.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PodAutoscalerSpecScaleTargetRef.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PodAutoscalerSpecScaleTargetRef."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["PodAutoscalerSpecScaleTargetRef", Builder]:
        return GenericListBuilder[
            PodAutoscalerSpecScaleTargetRef, PodAutoscalerSpecScaleTargetRef.Builder
        ]()

    api_version: Annotated[str | None, Field(alias="apiVersion")] = None
    "API version of the referent."
    kind: str | None = None
    "Kind of the referent.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    name: str | None = None
    "Name of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"


class PodAutoscalerStatusConditionsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PodAutoscalerStatusConditionsItem"]:
            return PodAutoscalerStatusConditionsItem

        def build(self) -> "PodAutoscalerStatusConditionsItem":
            return PodAutoscalerStatusConditionsItem(**self._attrs)

        def last_transition_time(self, value: str | None, /) -> Self:
            "LastTransitionTime is the last time the condition transitioned from one status to another.\nWe use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic\ndifferences (all other things held constant)."
            return self._set("last_transition_time", value)

        def message(self, value: str | None, /) -> Self:
            "A human readable message indicating details about the transition."
            return self._set("message", value)

        def reason(self, value: str | None, /) -> Self:
            "The reason for the condition\u0027s last transition."
            return self._set("reason", value)

        def severity(self, value: str | None, /) -> Self:
            "Severity with which to treat failures of this type of condition.\nWhen this is not specified, it defaults to Error."
            return self._set("severity", value)

        def status(self, value: str, /) -> Self:
            "Status of the condition, one of True, False, Unknown."
            return self._set("status", value)

        def type(self, value: str, /) -> Self:
            "Type of condition."
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["PodAutoscalerStatusConditionsItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PodAutoscalerStatusConditionsItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PodAutoscalerStatusConditionsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["PodAutoscalerStatusConditionsItem", Builder]:
        return GenericListBuilder[
            PodAutoscalerStatusConditionsItem, PodAutoscalerStatusConditionsItem.Builder
        ]()

    last_transition_time: Annotated[str | None, Field(alias="lastTransitionTime")] = None
    "LastTransitionTime is the last time the condition transitioned from one status to another.\nWe use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic\ndifferences (all other things held constant)."
    message: str | None = None
    "A human readable message indicating details about the transition."
    reason: str | None = None
    "The reason for the condition\u0027s last transition."
    severity: str | None = None
    "Severity with which to treat failures of this type of condition.\nWhen this is not specified, it defaults to Error."
    status: str
    "Status of the condition, one of True, False, Unknown."
    type: str
    "Type of condition."


class MetricStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["MetricStatus"]:
            return MetricStatus

        def build(self) -> "MetricStatus":
            return MetricStatus(**self._attrs)

        def annotations(self, value: dict[str, str] | None, /) -> Self:
            "Annotations is additional Status fields for the Resource to save some\nadditional State as well as convey more information to the user. This is\nroughly akin to Annotations on any k8s resource, just the reconciler conveying\nricher information outwards."
            return self._set("annotations", value)

        @overload
        def conditions(
            self, value_or_callback: list[MetricStatusConditionsItem] | None, /
        ) -> "MetricStatus.Builder": ...

        @overload
        def conditions(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        MetricStatusConditionsItem, MetricStatusConditionsItem.Builder
                    ]
                ],
                GenericListBuilder[MetricStatusConditionsItem, MetricStatusConditionsItem.Builder]
                | list[MetricStatusConditionsItem],
            ],
            /,
        ) -> "MetricStatus.Builder": ...

        @overload
        def conditions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[MetricStatusConditionsItem.Builder]: ...

        def conditions(self, value_or_callback=UNSET, /):
            "Conditions the latest available observations of a resource\u0027s current state."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[MetricStatusConditionsItem.Builder]()
                context._parent_builder = self
                context._field_name = "conditions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(MetricStatusConditionsItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("conditions", value)

        def observed_generation(self, value: int | None, /) -> Self:
            "ObservedGeneration is the \u0027Generation\u0027 of the Service that\nwas last processed by the controller."
            return self._set("observed_generation", value)

    class BuilderContext(BuilderContextBase["MetricStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = MetricStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for MetricStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["MetricStatus", Builder]:
        return GenericListBuilder[MetricStatus, MetricStatus.Builder]()

    annotations: dict[str, str] | None = None
    "Annotations is additional Status fields for the Resource to save some\nadditional State as well as convey more information to the user. This is\nroughly akin to Annotations on any k8s resource, just the reconciler conveying\nricher information outwards."
    conditions: list[MetricStatusConditionsItem] | None = None
    "Conditions the latest available observations of a resource\u0027s current state."
    observed_generation: Annotated[int | None, Field(alias="observedGeneration")] = None
    "ObservedGeneration is the \u0027Generation\u0027 of the Service that\nwas last processed by the controller."


class PodAutoscalerSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PodAutoscalerSpec"]:
            return PodAutoscalerSpec

        def build(self) -> "PodAutoscalerSpec":
            return PodAutoscalerSpec(**self._attrs)

        def container_concurrency(self, value: int | None, /) -> Self:
            "ContainerConcurrency specifies the maximum allowed\nin-flight (concurrent) requests per container of the Revision.\nDefaults to `0` which means unlimited concurrency."
            return self._set("container_concurrency", value)

        def protocol_type(self, value: str, /) -> Self:
            "The application-layer protocol. Matches `ProtocolType` inferred from the revision spec."
            return self._set("protocol_type", value)

        def reachability(self, value: str | None, /) -> Self:
            "Reachability specifies whether or not the `ScaleTargetRef` can be reached (ie. has a route).\nDefaults to `ReachabilityUnknown`"
            return self._set("reachability", value)

        @overload
        def scale_target_ref(
            self, value_or_callback: PodAutoscalerSpecScaleTargetRef, /
        ) -> "PodAutoscalerSpec.Builder": ...

        @overload
        def scale_target_ref(
            self,
            value_or_callback: Callable[
                [PodAutoscalerSpecScaleTargetRef.Builder],
                PodAutoscalerSpecScaleTargetRef.Builder | PodAutoscalerSpecScaleTargetRef,
            ],
            /,
        ) -> "PodAutoscalerSpec.Builder": ...

        @overload
        def scale_target_ref(
            self, value_or_callback: Never = ...
        ) -> "PodAutoscalerSpecScaleTargetRef.BuilderContext": ...

        def scale_target_ref(self, value_or_callback=UNSET, /):
            "ScaleTargetRef defines the /scale-able resource that this PodAutoscaler\nis responsible for quickly right-sizing."
            if self._in_context and value_or_callback is UNSET:
                context = PodAutoscalerSpecScaleTargetRef.BuilderContext()
                context._parent_builder = self
                context._field_name = "scale_target_ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PodAutoscalerSpecScaleTargetRef.builder())
                if isinstance(output, PodAutoscalerSpecScaleTargetRef.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("scale_target_ref", value)

    class BuilderContext(BuilderContextBase["PodAutoscalerSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PodAutoscalerSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PodAutoscalerSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["PodAutoscalerSpec", Builder]:
        return GenericListBuilder[PodAutoscalerSpec, PodAutoscalerSpec.Builder]()

    container_concurrency: Annotated[int | None, Field(alias="containerConcurrency")] = None
    "ContainerConcurrency specifies the maximum allowed\nin-flight (concurrent) requests per container of the Revision.\nDefaults to `0` which means unlimited concurrency."
    protocol_type: Annotated[str, Field(alias="protocolType")]
    "The application-layer protocol. Matches `ProtocolType` inferred from the revision spec."
    reachability: str | None = None
    "Reachability specifies whether or not the `ScaleTargetRef` can be reached (ie. has a route).\nDefaults to `ReachabilityUnknown`"
    scale_target_ref: Annotated[PodAutoscalerSpecScaleTargetRef, Field(alias="scaleTargetRef")]
    "ScaleTargetRef defines the /scale-able resource that this PodAutoscaler\nis responsible for quickly right-sizing."


class PodAutoscalerStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PodAutoscalerStatus"]:
            return PodAutoscalerStatus

        def build(self) -> "PodAutoscalerStatus":
            return PodAutoscalerStatus(**self._attrs)

        def actual_scale(self, value: int | None, /) -> Self:
            "ActualScale shows the actual number of replicas for the revision."
            return self._set("actual_scale", value)

        def annotations(self, value: dict[str, str] | None, /) -> Self:
            "Annotations is additional Status fields for the Resource to save some\nadditional State as well as convey more information to the user. This is\nroughly akin to Annotations on any k8s resource, just the reconciler conveying\nricher information outwards."
            return self._set("annotations", value)

        @overload
        def conditions(
            self, value_or_callback: list[PodAutoscalerStatusConditionsItem] | None, /
        ) -> "PodAutoscalerStatus.Builder": ...

        @overload
        def conditions(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        PodAutoscalerStatusConditionsItem,
                        PodAutoscalerStatusConditionsItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    PodAutoscalerStatusConditionsItem,
                    PodAutoscalerStatusConditionsItem.Builder,
                ]
                | list[PodAutoscalerStatusConditionsItem],
            ],
            /,
        ) -> "PodAutoscalerStatus.Builder": ...

        @overload
        def conditions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[PodAutoscalerStatusConditionsItem.Builder]: ...

        def conditions(self, value_or_callback=UNSET, /):
            "Conditions the latest available observations of a resource\u0027s current state."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[PodAutoscalerStatusConditionsItem.Builder]()
                context._parent_builder = self
                context._field_name = "conditions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PodAutoscalerStatusConditionsItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("conditions", value)

        def desired_scale(self, value: int | None, /) -> Self:
            "DesiredScale shows the current desired number of replicas for the revision."
            return self._set("desired_scale", value)

        def metrics_service_name(self, value: str, /) -> Self:
            "MetricsServiceName is the K8s Service name that provides revision metrics.\nThe service is managed by the PA object."
            return self._set("metrics_service_name", value)

        def observed_generation(self, value: int | None, /) -> Self:
            "ObservedGeneration is the \u0027Generation\u0027 of the Service that\nwas last processed by the controller."
            return self._set("observed_generation", value)

        def service_name(self, value: str, /) -> Self:
            "ServiceName is the K8s Service name that serves the revision, scaled by this PA.\nThe service is created and owned by the ServerlessService object owned by this PA."
            return self._set("service_name", value)

    class BuilderContext(BuilderContextBase["PodAutoscalerStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PodAutoscalerStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PodAutoscalerStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["PodAutoscalerStatus", Builder]:
        return GenericListBuilder[PodAutoscalerStatus, PodAutoscalerStatus.Builder]()

    actual_scale: Annotated[int | None, Field(alias="actualScale")] = None
    "ActualScale shows the actual number of replicas for the revision."
    annotations: dict[str, str] | None = None
    "Annotations is additional Status fields for the Resource to save some\nadditional State as well as convey more information to the user. This is\nroughly akin to Annotations on any k8s resource, just the reconciler conveying\nricher information outwards."
    conditions: list[PodAutoscalerStatusConditionsItem] | None = None
    "Conditions the latest available observations of a resource\u0027s current state."
    desired_scale: Annotated[int | None, Field(alias="desiredScale")] = None
    "DesiredScale shows the current desired number of replicas for the revision."
    metrics_service_name: Annotated[str, Field(alias="metricsServiceName")]
    "MetricsServiceName is the K8s Service name that provides revision metrics.\nThe service is managed by the PA object."
    observed_generation: Annotated[int | None, Field(alias="observedGeneration")] = None
    "ObservedGeneration is the \u0027Generation\u0027 of the Service that\nwas last processed by the controller."
    service_name: Annotated[str, Field(alias="serviceName")]
    "ServiceName is the K8s Service name that serves the revision, scaled by this PA.\nThe service is created and owned by the ServerlessService object owned by this PA."


class Metric(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "metrics",
        "scope": "Namespaced",
        "status": True,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["Metric"]:
            return Metric

        def build(self) -> "Metric":
            return Metric(**self._attrs)

        def api_version(
            self, value: Literal["autoscaling.internal.knative.dev/v1alpha1"], /
        ) -> Self:
            "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["Metric"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(self, value_or_callback: ObjectMeta | None, /) -> "Metric.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "Metric.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(self, value_or_callback: MetricSpec | None, /) -> "Metric.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[[MetricSpec.Builder], MetricSpec.Builder | MetricSpec],
            /,
        ) -> "Metric.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "MetricSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = MetricSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(MetricSpec.builder())
                if isinstance(output, MetricSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(self, value_or_callback: MetricStatus | None, /) -> "Metric.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [MetricStatus.Builder], MetricStatus.Builder | MetricStatus
            ],
            /,
        ) -> "Metric.Builder": ...

        @overload
        def status(self, value_or_callback: Never = ...) -> "MetricStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = MetricStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(MetricStatus.builder())
                if isinstance(output, MetricStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["Metric.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = Metric.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for Metric."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["Metric", Builder]:
        return GenericListBuilder[Metric, Metric.Builder]()

    api_version: Annotated[
        Literal["autoscaling.internal.knative.dev/v1alpha1"], Field(alias="apiVersion")
    ] = "autoscaling.internal.knative.dev/v1alpha1"
    "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["Metric"] = "Metric"
    "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    spec: MetricSpec | None = None
    status: MetricStatus | None = None


class PodAutoscaler(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "podautoscalers",
        "scope": "Namespaced",
        "status": True,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PodAutoscaler"]:
            return PodAutoscaler

        def build(self) -> "PodAutoscaler":
            return PodAutoscaler(**self._attrs)

        def api_version(
            self, value: Literal["autoscaling.internal.knative.dev/v1alpha1"], /
        ) -> Self:
            "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["PodAutoscaler"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(self, value_or_callback: ObjectMeta | None, /) -> "PodAutoscaler.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "PodAutoscaler.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(
            self, value_or_callback: PodAutoscalerSpec | None, /
        ) -> "PodAutoscaler.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [PodAutoscalerSpec.Builder],
                PodAutoscalerSpec.Builder | PodAutoscalerSpec,
            ],
            /,
        ) -> "PodAutoscaler.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "PodAutoscalerSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = PodAutoscalerSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PodAutoscalerSpec.builder())
                if isinstance(output, PodAutoscalerSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(
            self, value_or_callback: PodAutoscalerStatus | None, /
        ) -> "PodAutoscaler.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [PodAutoscalerStatus.Builder],
                PodAutoscalerStatus.Builder | PodAutoscalerStatus,
            ],
            /,
        ) -> "PodAutoscaler.Builder": ...

        @overload
        def status(
            self, value_or_callback: Never = ...
        ) -> "PodAutoscalerStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = PodAutoscalerStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PodAutoscalerStatus.builder())
                if isinstance(output, PodAutoscalerStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["PodAutoscaler.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PodAutoscaler.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PodAutoscaler."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["PodAutoscaler", Builder]:
        return GenericListBuilder[PodAutoscaler, PodAutoscaler.Builder]()

    api_version: Annotated[
        Literal["autoscaling.internal.knative.dev/v1alpha1"], Field(alias="apiVersion")
    ] = "autoscaling.internal.knative.dev/v1alpha1"
    "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["PodAutoscaler"] = "PodAutoscaler"
    "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    spec: PodAutoscalerSpec | None = None
    status: PodAutoscalerStatus | None = None
