# Generated by cloudcoil-model-codegen v0.7.0
# DO NOT EDIT

from typing import Annotated, Callable, ClassVar, Literal, overload

from cloudcoil.apimachinery import ObjectMeta
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)
from cloudcoil.resources import Resource
from pydantic import Field


class DomainMappingSpecRef(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DomainMappingSpecRef"]:
            return DomainMappingSpecRef

        def build(self) -> "DomainMappingSpecRef":
            return DomainMappingSpecRef(**self._attrs)

        def address(self, value: str | None, /) -> Self:
            "Address points to a specific Address Name."
            return self._set("address", value)

        def api_version(self, value: str | None, /) -> Self:
            "API version of the referent."
            return self._set("api_version", value)

        def group(self, value: str | None, /) -> Self:
            "Group of the API, without the version of the group. This can be used as an alternative to the APIVersion, and then resolved using ResolveGroup.\nNote: This API is EXPERIMENTAL and might break anytime. For more details: https://github.com/knative/eventing/issues/5086"
            return self._set("group", value)

        def kind(self, value: str, /) -> Self:
            "Kind of the referent.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        def name(self, value: str, /) -> Self:
            "Name of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
            return self._set("name", value)

        def namespace(self, value: str | None, /) -> Self:
            "Namespace of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/\nThis is optional field, it gets defaulted to the object holding it if left out."
            return self._set("namespace", value)

    class BuilderContext(BuilderContextBase["DomainMappingSpecRef.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DomainMappingSpecRef.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DomainMappingSpecRef."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["DomainMappingSpecRef", Builder]:
        return GenericListBuilder[DomainMappingSpecRef, DomainMappingSpecRef.Builder]()

    address: str | None = None
    "Address points to a specific Address Name."
    api_version: Annotated[str | None, Field(alias="apiVersion")] = None
    "API version of the referent."
    group: str | None = None
    "Group of the API, without the version of the group. This can be used as an alternative to the APIVersion, and then resolved using ResolveGroup.\nNote: This API is EXPERIMENTAL and might break anytime. For more details: https://github.com/knative/eventing/issues/5086"
    kind: str
    "Kind of the referent.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    name: str
    "Name of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
    namespace: str | None = None
    "Namespace of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/\nThis is optional field, it gets defaulted to the object holding it if left out."


class DomainMappingSpecTls(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DomainMappingSpecTls"]:
            return DomainMappingSpecTls

        def build(self) -> "DomainMappingSpecTls":
            return DomainMappingSpecTls(**self._attrs)

        def secret_name(self, value: str, /) -> Self:
            "SecretName is the name of the existing secret used to terminate TLS traffic."
            return self._set("secret_name", value)

    class BuilderContext(BuilderContextBase["DomainMappingSpecTls.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DomainMappingSpecTls.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DomainMappingSpecTls."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["DomainMappingSpecTls", Builder]:
        return GenericListBuilder[DomainMappingSpecTls, DomainMappingSpecTls.Builder]()

    secret_name: Annotated[str, Field(alias="secretName")]
    "SecretName is the name of the existing secret used to terminate TLS traffic."


class DomainMappingStatusAddress(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DomainMappingStatusAddress"]:
            return DomainMappingStatusAddress

        def build(self) -> "DomainMappingStatusAddress":
            return DomainMappingStatusAddress(**self._attrs)

        def ca_certs(self, value: str | None, /) -> Self:
            "CACerts is the Certification Authority (CA) certificates in PEM format\naccording to https://www.rfc-editor.org/rfc/rfc7468."
            return self._set("ca_certs", value)

        def audience(self, value: str | None, /) -> Self:
            "Audience is the OIDC audience for this address."
            return self._set("audience", value)

        def name(self, value: str | None, /) -> Self:
            "Name is the name of the address."
            return self._set("name", value)

        def url(self, value: str | None, /) -> Self:
            return self._set("url", value)

    class BuilderContext(BuilderContextBase["DomainMappingStatusAddress.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DomainMappingStatusAddress.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DomainMappingStatusAddress."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["DomainMappingStatusAddress", Builder]:
        return GenericListBuilder[DomainMappingStatusAddress, DomainMappingStatusAddress.Builder]()

    ca_certs: Annotated[str | None, Field(alias="CACerts")] = None
    "CACerts is the Certification Authority (CA) certificates in PEM format\naccording to https://www.rfc-editor.org/rfc/rfc7468."
    audience: str | None = None
    "Audience is the OIDC audience for this address."
    name: str | None = None
    "Name is the name of the address."
    url: str | None = None


class DomainMappingStatusConditionsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DomainMappingStatusConditionsItem"]:
            return DomainMappingStatusConditionsItem

        def build(self) -> "DomainMappingStatusConditionsItem":
            return DomainMappingStatusConditionsItem(**self._attrs)

        def last_transition_time(self, value: str | None, /) -> Self:
            "LastTransitionTime is the last time the condition transitioned from one status to another.\nWe use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic\ndifferences (all other things held constant)."
            return self._set("last_transition_time", value)

        def message(self, value: str | None, /) -> Self:
            "A human readable message indicating details about the transition."
            return self._set("message", value)

        def reason(self, value: str | None, /) -> Self:
            "The reason for the condition\u0027s last transition."
            return self._set("reason", value)

        def severity(self, value: str | None, /) -> Self:
            "Severity with which to treat failures of this type of condition.\nWhen this is not specified, it defaults to Error."
            return self._set("severity", value)

        def status(self, value: str, /) -> Self:
            "Status of the condition, one of True, False, Unknown."
            return self._set("status", value)

        def type(self, value: str, /) -> Self:
            "Type of condition."
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["DomainMappingStatusConditionsItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DomainMappingStatusConditionsItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DomainMappingStatusConditionsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["DomainMappingStatusConditionsItem", Builder]:
        return GenericListBuilder[
            DomainMappingStatusConditionsItem, DomainMappingStatusConditionsItem.Builder
        ]()

    last_transition_time: Annotated[str | None, Field(alias="lastTransitionTime")] = None
    "LastTransitionTime is the last time the condition transitioned from one status to another.\nWe use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic\ndifferences (all other things held constant)."
    message: str | None = None
    "A human readable message indicating details about the transition."
    reason: str | None = None
    "The reason for the condition\u0027s last transition."
    severity: str | None = None
    "Severity with which to treat failures of this type of condition.\nWhen this is not specified, it defaults to Error."
    status: str
    "Status of the condition, one of True, False, Unknown."
    type: str
    "Type of condition."


class DomainMappingSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DomainMappingSpec"]:
            return DomainMappingSpec

        def build(self) -> "DomainMappingSpec":
            return DomainMappingSpec(**self._attrs)

        @overload
        def ref(
            self, value_or_callback: DomainMappingSpecRef, /
        ) -> "DomainMappingSpec.Builder": ...

        @overload
        def ref(
            self,
            value_or_callback: Callable[
                [DomainMappingSpecRef.Builder],
                DomainMappingSpecRef.Builder | DomainMappingSpecRef,
            ],
            /,
        ) -> "DomainMappingSpec.Builder": ...

        @overload
        def ref(self, value_or_callback: Never = ...) -> "DomainMappingSpecRef.BuilderContext": ...

        def ref(self, value_or_callback=UNSET, /):
            "Ref specifies the target of the Domain Mapping.\n\nThe object identified by the Ref must be an Addressable with a URL of the\nform `{name}.{namespace}.{domain}` where `{domain}` is the cluster domain,\nand `{name}` and `{namespace}` are the name and namespace of a Kubernetes\nService.\n\nThis contract is satisfied by Knative types such as Knative Services and\nKnative Routes, and by Kubernetes Services."
            if self._in_context and value_or_callback is UNSET:
                context = DomainMappingSpecRef.BuilderContext()
                context._parent_builder = self
                context._field_name = "ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(DomainMappingSpecRef.builder())
                if isinstance(output, DomainMappingSpecRef.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("ref", value)

        @overload
        def tls(
            self, value_or_callback: DomainMappingSpecTls | None, /
        ) -> "DomainMappingSpec.Builder": ...

        @overload
        def tls(
            self,
            value_or_callback: Callable[
                [DomainMappingSpecTls.Builder],
                DomainMappingSpecTls.Builder | DomainMappingSpecTls,
            ],
            /,
        ) -> "DomainMappingSpec.Builder": ...

        @overload
        def tls(self, value_or_callback: Never = ...) -> "DomainMappingSpecTls.BuilderContext": ...

        def tls(self, value_or_callback=UNSET, /):
            "TLS allows the DomainMapping to terminate TLS traffic with an existing secret."
            if self._in_context and value_or_callback is UNSET:
                context = DomainMappingSpecTls.BuilderContext()
                context._parent_builder = self
                context._field_name = "tls"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(DomainMappingSpecTls.builder())
                if isinstance(output, DomainMappingSpecTls.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("tls", value)

    class BuilderContext(BuilderContextBase["DomainMappingSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DomainMappingSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DomainMappingSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["DomainMappingSpec", Builder]:
        return GenericListBuilder[DomainMappingSpec, DomainMappingSpec.Builder]()

    ref: DomainMappingSpecRef
    "Ref specifies the target of the Domain Mapping.\n\nThe object identified by the Ref must be an Addressable with a URL of the\nform `{name}.{namespace}.{domain}` where `{domain}` is the cluster domain,\nand `{name}` and `{namespace}` are the name and namespace of a Kubernetes\nService.\n\nThis contract is satisfied by Knative types such as Knative Services and\nKnative Routes, and by Kubernetes Services."
    tls: DomainMappingSpecTls | None = None
    "TLS allows the DomainMapping to terminate TLS traffic with an existing secret."


class DomainMappingStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DomainMappingStatus"]:
            return DomainMappingStatus

        def build(self) -> "DomainMappingStatus":
            return DomainMappingStatus(**self._attrs)

        @overload
        def address(
            self, value_or_callback: DomainMappingStatusAddress | None, /
        ) -> "DomainMappingStatus.Builder": ...

        @overload
        def address(
            self,
            value_or_callback: Callable[
                [DomainMappingStatusAddress.Builder],
                DomainMappingStatusAddress.Builder | DomainMappingStatusAddress,
            ],
            /,
        ) -> "DomainMappingStatus.Builder": ...

        @overload
        def address(
            self, value_or_callback: Never = ...
        ) -> "DomainMappingStatusAddress.BuilderContext": ...

        def address(self, value_or_callback=UNSET, /):
            "Address holds the information needed for a DomainMapping to be the target of an event."
            if self._in_context and value_or_callback is UNSET:
                context = DomainMappingStatusAddress.BuilderContext()
                context._parent_builder = self
                context._field_name = "address"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(DomainMappingStatusAddress.builder())
                if isinstance(output, DomainMappingStatusAddress.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("address", value)

        def annotations(self, value: dict[str, str] | None, /) -> Self:
            "Annotations is additional Status fields for the Resource to save some\nadditional State as well as convey more information to the user. This is\nroughly akin to Annotations on any k8s resource, just the reconciler conveying\nricher information outwards."
            return self._set("annotations", value)

        @overload
        def conditions(
            self, value_or_callback: list[DomainMappingStatusConditionsItem] | None, /
        ) -> "DomainMappingStatus.Builder": ...

        @overload
        def conditions(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        DomainMappingStatusConditionsItem,
                        DomainMappingStatusConditionsItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    DomainMappingStatusConditionsItem,
                    DomainMappingStatusConditionsItem.Builder,
                ]
                | list[DomainMappingStatusConditionsItem],
            ],
            /,
        ) -> "DomainMappingStatus.Builder": ...

        @overload
        def conditions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[DomainMappingStatusConditionsItem.Builder]: ...

        def conditions(self, value_or_callback=UNSET, /):
            "Conditions the latest available observations of a resource\u0027s current state."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[DomainMappingStatusConditionsItem.Builder]()
                context._parent_builder = self
                context._field_name = "conditions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(DomainMappingStatusConditionsItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("conditions", value)

        def observed_generation(self, value: int | None, /) -> Self:
            "ObservedGeneration is the \u0027Generation\u0027 of the Service that\nwas last processed by the controller."
            return self._set("observed_generation", value)

        def url(self, value: str | None, /) -> Self:
            "URL is the URL of this DomainMapping."
            return self._set("url", value)

    class BuilderContext(BuilderContextBase["DomainMappingStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DomainMappingStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DomainMappingStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["DomainMappingStatus", Builder]:
        return GenericListBuilder[DomainMappingStatus, DomainMappingStatus.Builder]()

    address: DomainMappingStatusAddress | None = None
    "Address holds the information needed for a DomainMapping to be the target of an event."
    annotations: dict[str, str] | None = None
    "Annotations is additional Status fields for the Resource to save some\nadditional State as well as convey more information to the user. This is\nroughly akin to Annotations on any k8s resource, just the reconciler conveying\nricher information outwards."
    conditions: list[DomainMappingStatusConditionsItem] | None = None
    "Conditions the latest available observations of a resource\u0027s current state."
    observed_generation: Annotated[int | None, Field(alias="observedGeneration")] = None
    "ObservedGeneration is the \u0027Generation\u0027 of the Service that\nwas last processed by the controller."
    url: str | None = None
    "URL is the URL of this DomainMapping."


class DomainMapping(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "domainmappings",
        "scope": "Namespaced",
        "status": True,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DomainMapping"]:
            return DomainMapping

        def build(self) -> "DomainMapping":
            return DomainMapping(**self._attrs)

        def api_version(self, value: Literal["serving.knative.dev/v1beta1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["DomainMapping"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(self, value_or_callback: ObjectMeta | None, /) -> "DomainMapping.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "DomainMapping.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(
            self, value_or_callback: DomainMappingSpec | None, /
        ) -> "DomainMapping.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [DomainMappingSpec.Builder],
                DomainMappingSpec.Builder | DomainMappingSpec,
            ],
            /,
        ) -> "DomainMapping.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "DomainMappingSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = DomainMappingSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(DomainMappingSpec.builder())
                if isinstance(output, DomainMappingSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(
            self, value_or_callback: DomainMappingStatus | None, /
        ) -> "DomainMapping.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [DomainMappingStatus.Builder],
                DomainMappingStatus.Builder | DomainMappingStatus,
            ],
            /,
        ) -> "DomainMapping.Builder": ...

        @overload
        def status(
            self, value_or_callback: Never = ...
        ) -> "DomainMappingStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = DomainMappingStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(DomainMappingStatus.builder())
                if isinstance(output, DomainMappingStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["DomainMapping.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DomainMapping.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DomainMapping."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["DomainMapping", Builder]:
        return GenericListBuilder[DomainMapping, DomainMapping.Builder]()

    api_version: Annotated[Literal["serving.knative.dev/v1beta1"], Field(alias="apiVersion")] = (
        "serving.knative.dev/v1beta1"
    )
    "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["DomainMapping"] = "DomainMapping"
    "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    spec: DomainMappingSpec | None = None
    status: DomainMappingStatus | None = None
