# Generated by cloudcoil-model-codegen v0.7.1
# DO NOT EDIT

from . import autoscaling_internal_knative_dev as autoscaling_internal_knative_dev
from . import caching_internal_knative_dev as caching_internal_knative_dev
from . import networking_internal_knative_dev as networking_internal_knative_dev
from . import serving_knative_dev as serving_knative_dev
from ._lookup import get_model as get_model
