# Generated by cloudcoil-model-codegen; DO NOT EDIT
from importlib import import_module
from typing import TYPE_CHECKING, Literal, overload

from cloudcoil.resources import Resource

if TYPE_CHECKING:
    from cloudcoil.models.knative_serving.internal.autoscaling.v1alpha1 import Metric as _Resource6
    from cloudcoil.models.knative_serving.internal.autoscaling.v1alpha1 import (
        PodAutoscaler as _Resource7,
    )
    from cloudcoil.models.knative_serving.internal.caching.v1alpha1 import Image as _Resource4
    from cloudcoil.models.knative_serving.internal.networking.v1alpha1 import (
        Certificate as _Resource0,
    )
    from cloudcoil.models.knative_serving.internal.networking.v1alpha1 import (
        ClusterDomainClaim as _Resource1,
    )
    from cloudcoil.models.knative_serving.internal.networking.v1alpha1 import Ingress as _Resource5
    from cloudcoil.models.knative_serving.internal.networking.v1alpha1 import (
        ServerlessService as _Resource10,
    )
    from cloudcoil.models.knative_serving.serving.v1 import Configuration as _Resource2
    from cloudcoil.models.knative_serving.serving.v1 import Revision as _Resource8
    from cloudcoil.models.knative_serving.serving.v1 import Route as _Resource9
    from cloudcoil.models.knative_serving.serving.v1 import Service as _Resource11
    from cloudcoil.models.knative_serving.serving.v1beta1 import DomainMapping as _Resource3

_MODELS = {
    ("Certificate", "networking.internal.knative.dev/v1alpha1"): (
        "cloudcoil.models.knative_serving.internal.networking.v1alpha1",
        "Certificate",
    ),
    ("Certificate", ""): (
        "cloudcoil.models.knative_serving.internal.networking.v1alpha1",
        "Certificate",
    ),
    ("ClusterDomainClaim", "networking.internal.knative.dev/v1alpha1"): (
        "cloudcoil.models.knative_serving.internal.networking.v1alpha1",
        "ClusterDomainClaim",
    ),
    ("ClusterDomainClaim", ""): (
        "cloudcoil.models.knative_serving.internal.networking.v1alpha1",
        "ClusterDomainClaim",
    ),
    ("Configuration", "serving.knative.dev/v1"): (
        "cloudcoil.models.knative_serving.serving.v1",
        "Configuration",
    ),
    ("Configuration", ""): ("cloudcoil.models.knative_serving.serving.v1", "Configuration"),
    ("DomainMapping", "serving.knative.dev/v1beta1"): (
        "cloudcoil.models.knative_serving.serving.v1beta1",
        "DomainMapping",
    ),
    ("DomainMapping", ""): ("cloudcoil.models.knative_serving.serving.v1beta1", "DomainMapping"),
    ("Image", "caching.internal.knative.dev/v1alpha1"): (
        "cloudcoil.models.knative_serving.internal.caching.v1alpha1",
        "Image",
    ),
    ("Image", ""): ("cloudcoil.models.knative_serving.internal.caching.v1alpha1", "Image"),
    ("Ingress", "networking.internal.knative.dev/v1alpha1"): (
        "cloudcoil.models.knative_serving.internal.networking.v1alpha1",
        "Ingress",
    ),
    ("Ingress", ""): ("cloudcoil.models.knative_serving.internal.networking.v1alpha1", "Ingress"),
    ("Metric", "autoscaling.internal.knative.dev/v1alpha1"): (
        "cloudcoil.models.knative_serving.internal.autoscaling.v1alpha1",
        "Metric",
    ),
    ("Metric", ""): ("cloudcoil.models.knative_serving.internal.autoscaling.v1alpha1", "Metric"),
    ("PodAutoscaler", "autoscaling.internal.knative.dev/v1alpha1"): (
        "cloudcoil.models.knative_serving.internal.autoscaling.v1alpha1",
        "PodAutoscaler",
    ),
    ("PodAutoscaler", ""): (
        "cloudcoil.models.knative_serving.internal.autoscaling.v1alpha1",
        "PodAutoscaler",
    ),
    ("Revision", "serving.knative.dev/v1"): (
        "cloudcoil.models.knative_serving.serving.v1",
        "Revision",
    ),
    ("Revision", ""): ("cloudcoil.models.knative_serving.serving.v1", "Revision"),
    ("Route", "serving.knative.dev/v1"): ("cloudcoil.models.knative_serving.serving.v1", "Route"),
    ("Route", ""): ("cloudcoil.models.knative_serving.serving.v1", "Route"),
    ("ServerlessService", "networking.internal.knative.dev/v1alpha1"): (
        "cloudcoil.models.knative_serving.internal.networking.v1alpha1",
        "ServerlessService",
    ),
    ("ServerlessService", ""): (
        "cloudcoil.models.knative_serving.internal.networking.v1alpha1",
        "ServerlessService",
    ),
    ("Service", "serving.knative.dev/v1"): (
        "cloudcoil.models.knative_serving.serving.v1",
        "Service",
    ),
    ("Service", ""): ("cloudcoil.models.knative_serving.serving.v1", "Service"),
}


@overload
def get_model(
    kind: Literal["Certificate"],
    *,
    api_version: Literal["networking.internal.knative.dev/v1alpha1"],
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["Certificate"], *, api_version: Literal[""] = ""
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["ClusterDomainClaim"],
    *,
    api_version: Literal["networking.internal.knative.dev/v1alpha1"],
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["ClusterDomainClaim"], *, api_version: Literal[""] = ""
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["Configuration"], *, api_version: Literal["serving.knative.dev/v1"]
) -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["Configuration"], *, api_version: Literal[""] = ""
) -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["DomainMapping"], *, api_version: Literal["serving.knative.dev/v1beta1"]
) -> type[_Resource3]: ...


@overload
def get_model(
    kind: Literal["DomainMapping"], *, api_version: Literal[""] = ""
) -> type[_Resource3]: ...


@overload
def get_model(
    kind: Literal["Image"], *, api_version: Literal["caching.internal.knative.dev/v1alpha1"]
) -> type[_Resource4]: ...


@overload
def get_model(kind: Literal["Image"], *, api_version: Literal[""] = "") -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["Ingress"], *, api_version: Literal["networking.internal.knative.dev/v1alpha1"]
) -> type[_Resource5]: ...


@overload
def get_model(kind: Literal["Ingress"], *, api_version: Literal[""] = "") -> type[_Resource5]: ...


@overload
def get_model(
    kind: Literal["Metric"], *, api_version: Literal["autoscaling.internal.knative.dev/v1alpha1"]
) -> type[_Resource6]: ...


@overload
def get_model(kind: Literal["Metric"], *, api_version: Literal[""] = "") -> type[_Resource6]: ...


@overload
def get_model(
    kind: Literal["PodAutoscaler"],
    *,
    api_version: Literal["autoscaling.internal.knative.dev/v1alpha1"],
) -> type[_Resource7]: ...


@overload
def get_model(
    kind: Literal["PodAutoscaler"], *, api_version: Literal[""] = ""
) -> type[_Resource7]: ...


@overload
def get_model(
    kind: Literal["Revision"], *, api_version: Literal["serving.knative.dev/v1"]
) -> type[_Resource8]: ...


@overload
def get_model(kind: Literal["Revision"], *, api_version: Literal[""] = "") -> type[_Resource8]: ...


@overload
def get_model(
    kind: Literal["Route"], *, api_version: Literal["serving.knative.dev/v1"]
) -> type[_Resource9]: ...


@overload
def get_model(kind: Literal["Route"], *, api_version: Literal[""] = "") -> type[_Resource9]: ...


@overload
def get_model(
    kind: Literal["ServerlessService"],
    *,
    api_version: Literal["networking.internal.knative.dev/v1alpha1"],
) -> type[_Resource10]: ...


@overload
def get_model(
    kind: Literal["ServerlessService"], *, api_version: Literal[""] = ""
) -> type[_Resource10]: ...


@overload
def get_model(
    kind: Literal["Service"], *, api_version: Literal["serving.knative.dev/v1"]
) -> type[_Resource11]: ...


@overload
def get_model(kind: Literal["Service"], *, api_version: Literal[""] = "") -> type[_Resource11]: ...


@overload
def get_model(kind: str, *, api_version: str = "") -> type[Resource]: ...


def get_model(kind: str, *, api_version: str = "") -> type[Resource]:
    """Look up a model in this package; specify api_version for ambiguous kinds."""
    try:
        module, name = _MODELS[kind, api_version]
    except KeyError:
        raise ValueError(
            f"Unknown or ambiguous resource {kind!r}; specify a supported api_version"
        ) from None
    return getattr(import_module(module), name)
